### ISSUE TITLE
(ToolTip ) System.ArgumentNullException: Value cannot be null. (Parameter 'element')

### ISSUE THREAD

**Issue by hhu-mahmoud** [dotnet/wpf#6319]
* .NET Core Version: 6.0.3
* Windows version: Win10
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)?: No

 **Problem description:**
 App Crash .. the Problem should be resolved but it comes again and again.
 
 BTW: I don't use any Tooltip in my App, regardless the problem come again and again during the working!
 
 **Actual behavior:** 
 
 Application: Project.exe
CoreCLR Version: 6.0.322.12309
.NET Version: 6.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
   at System.Windows.Controls.ToolTipService.GetBetweenShowDelay(DependencyObject element)
   at System.Windows.Controls.PopupControlService.CloseToolTip(ToolTip tooltip)
   at System.Windows.Controls.PopupControlService.OnPostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(Tuple`2 postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.MouseDevice.Synchronize()
   at System.Windows.Input.MouseDevice.ChangeMouseCapture(IInputElement mouseCapture, IMouseInputProvider providerCapture, CaptureMode captureMode, Int32 timestamp)
   at System.Windows.Input.MouseDevice.Capture(IInputElement element, CaptureMode captureMode)
   at CefSharp.Wpf.ChromiumWebBrowser.OnMouseDown(MouseButtonEventArgs e) in C:\projects\cefsharp\CefSharp.Wpf\ChromiumWebBrowser.cs:line 2239
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Application.Desktop.App.Main()

 
 **Expected behavior:**
 App should not be crashed

How could i solve the Problem fastly ?

**Comment by Symbai** [comment]
Can you try running it on 6.0.2? There is a [known issue](https://github.com/dotnet/wpf/pull/6300) introduced with 6.0.3 related to Popupcontrolservice

**Comment by hhu-mahmoud** [comment]
> Can you try running it on 6.0.2? There is a [known issue](https://github.com/dotnet/wpf/pull/6300) introduced with 6.0.3 related to Popupcontrolservice

@Symbai it was also on 6.0.2. I wait for the Update of 6.0.3 but it still exist !! I need a workaround until they solve this problem.

**Comment by SamBent** [comment]
@hhu-mahmoud - Your app clearly _is_ using tooltips, otherwise it wouldn't reach this codepath.  The tooltips probably belong to built-in controls or to 3rd party controls that your app uses, so your app doesn't declare them directly. 

The diagnosis and proposed fix from @amaitland doesn't go deep enough.  A codepath that reaches that far into CloseToolTip should have `owner != null`;  this is true in all our tests and in every example we've seen.  So your app (or probably the 3rd party control) is doing something unusual while opening or closing the tooltip.  We need to understand what that is, to avoid other problems that might be lying behind this crash.

Please attach (or link) a sample app that repros the crash.  (If it relies on 3rd party controls, include those as well - we need to be able to run your app and debug the behavior that leads to the crash.)  If that's not feasible, a [time-travel trace](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-record#attach-to-a-process) of the crash is the next best thing.

**Comment by amaitland** [comment]
@SamBent Thanks for the prompt reply 👍 

> What steps will reproduce the problem?

> Please provide detailed information here, enough for someone else to reproduce your problem.
It's hard to reproduce the problem. It comes during the working

As per https://github.com/cefsharp/CefSharp/issues/4048#issue-1183132694 The bug report completed by @hhu-mahmoud doesn't provide a reproduction unfortunately. 

> So your app (or probably the 3rd party control) is doing something unusual while opening or closing the tooltip. 

The code in question is part of CefSharp. 

- https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L537
- https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L2036
- https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L2058

A DispatcherTimer is used to delay showing the tooltip to better mimic the behaviour of chromium.

The same code works in every version of WPF prior to 6.

> The diagnosis and proposed fix from @amaitland doesn't go deep enough. 

No argument there, only have the stack trace to go by. It's not clear how owner is actually null, just that it is. 

> Please attach (or link) a sample app that repros the crash. (If it relies on 3rd party controls, include those as well - we need to be able to run your app and debug the behavior that leads to the crash.) If that's not feasible, a [time-travel trace](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-record#attach-to-a-process) of the crash is the next best thing.

I'll defer to @hhu-mahmoud here as I've yet to reproduce the issue myself.

**Comment by hhu-mahmoud** [comment]
@SamBent Thanks for reply.

@amaitland has said all information, what i have.

Actually i become everyday reports from employees, that the app crashed between 2 until 14 times per day with 8 Hours work. I tried to reproduce the problem on the developing machine but no thing happend and everything works fine. At the client PCs i copied the error as  StackTrace from "Windows Events" and I posted it here. 

I have downgraged the App to .Net5 and everything works since 2 days fine and perfect  and no one reported this problem. I asked the employees also and they are too happy with .Net5 because it makes no problems!!

I did not changed anything in the code just downgraded to .Net5 with exactly the same code.

I use 3rd party controls such as MahApps and CefSharp. I removed the MahApps but i still have the same error with ToolTip.

I don't use any ToolTip only the Standard ToolTips (Minimize, Maximize, Close) and this one:

![grafik](https://user-images.githubusercontent.com/32834850/160991681-d1771741-8491-410e-8ef8-47a963c0c155.png)

and it works fine with .Net5 and .Net6 this tooltip:

![grafik](https://user-images.githubusercontent.com/32834850/160991889-e46dd4ed-7b99-491e-91db-f6ce4e4693fe.png)

I use CefSharp as Browser and inside it should run a Website (Web Application) and this website has many tooltips inside it but it's a Website and it comes from outside and runs into a browser, regardless i have never had a problem with it, only with .Net6 and during the work in this Website the app crashs. It seems. that the app makes no problem, if i just start the app without working on the Website in the browser inside it (if the app in idle mode).  i can also post another stack trace from Windows Events, where the CefSharp is not menthioned

Application: Project.exe CoreCLR 
Version: 6.0.322.12309 
.NET Version: 6.0.3 
Description: The process was terminated due to an unhandled exception. Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'element') at System.Windows.Controls.ToolTipService.GetBetweenShowDelay(DependencyObject element) at System.Windows.Controls.PopupControlService.CloseToolTip(ToolTip tooltip) at System.Windows.Controls.PopupControlService.OnPostProcessInput(Object sender, ProcessInputEventArgs e) at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(Tuple`2 postProcessInput, ProcessInputEventArgs processInputEventArgs) at System.Windows.Input.InputManager.ProcessStagingArea() at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport) at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel) at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg) at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame) at System.Windows.Threading.Dispatcher.Run() at System.Windows.Application.RunDispatcher(Object ignore) at System.Windows.Application.RunInternal(Window window) at System.Windows.Application.Run() at Application.Desktop.App.Main()


I'm trying since 1 Hour to reproduce the errory myself but it too hard, because i don't work on the web application inside the app just trying to do some clicks

**Comment by SamBent** [comment]
To summarize what we know (or suspect):
* (suspect) The crash involves tooltips belonging to the CefSharp browser control, on behalf of the web content it displays
* (suspect) There is a race condition that leads to the crash.  "app crashed between 2 until 14 times per day"
* (know) CefSharp manages its tooltips in a non-standard way.  @amaitland showed us code that manipulates tooltips directly, instead of setting ToolTipService properties and letting WPF manipulate the tooltips accordingly.
* (know) You can't turn off WPF's logic completely.  WPF will respond to user actions by manipulating tooltips, for example if you move the mouse away from a control, WPF will try to close its tooltip.  That's what's happening in the callstacks.  (To be precise, the callstacks definitely show WPF trying to close a tooltip because of a user gesture, but they don't say which gesture.  Moving the mouse away is the most common reason, but it could be others:  deactivating the app (Alt-Tab), clicking the mouse, typing, etc.) 
* (suspect) The alleged race condition is between CefSharp's logic and WPF's.  In the example, CefSharp's direct manipulation has somehow broken WPF's assumption "owner != null".

To fix the bug correctly, we need to discover how CefSharp's logic interacts with WPF's, which of WPF's assumptions are not justified in light of CefSharp's direct manipulation, and what to do when they don't hold.  To that end:

@hhu-mahmoud Can you get more information from your users?  Specifically
* any patterns they have observed.  Does the crash always involve a particular tooltip, or a particular type of tooltip (e.g. "content is image", or "show-duration is > 10 seconds"?  Does it involve a particular gesture, or combination of gestures?  Best of all would be specific steps that crash reliably (or with high probablity).
* a [time-travel trace](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-record#attach-to-a-process) of the crash

@amaitland  Can you provide
* a [time-travel trace](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-record#attach-to-a-process) of the correct (non-crashing) behavior of opening and closing a CefSharp tooltip.
* pointers to all the tooltip code in CefSharp (in case the list you already shared isn't everything)
* even better, an app that contains CefSharp's tooltip logic, but nothing else.  I.e. no web functionality, just a couple of buttons whose tooltips are managed with your logic.

Besides fixing the bug, I want to add test coverage of the "direct manipulation" scenario, to prevent future regressions.  CefSharp isn't doing anything wrong AFAIK, but we're not testing what it does do.

**Comment by znakeeye** [comment]
This has nothing to do with `CefSharp`. It's a bug introduced in `.NET 6`. We have it in our pure WPF project too.

**Comment by hhu-mahmoud** [comment]
> This has nothing to do with `CefSharp`. It's a bug introduced in `.NET 6`. We have it in our pure WPF project too.

@znakeeye do have a way to reproduce the exception? it comes by us randomly during the working and we did not find a way to reproduce it with certain steps!

**Comment by kvijay22** [comment]
@SamBent 
We are also facing this issue. We upgraded recently to 6.0.x, We are constantly facing app crash. This issue occurs when tool tip is invoked as soon as xaml is loaded. This happens for wpf controls not any third party. 

CurrentDomain FirstChanceException
Message: Value cannot be null. (Parameter 'element') Type: System.ArgumentNullException
   at System.Environment.get_StackTrace()
   at ApplicationName.App.CurrentDomain_FirstChanceException(Object sender, FirstChanceExceptionEventArgs e) in App.xaml.cs:line 128
   at System.Windows.Controls.ToolTipService.GetBetweenShowDelay(DependencyObject element)
   at System.Windows.Controls.PopupControlService.CloseToolTip(ToolTip tooltip)
   at System.Windows.Controls.PopupControlService.PromotePendingToolTipToCurrent(TriggerAction triggerAction)
   at System.Windows.Controls.PopupControlService.<>c__DisplayClass9_0.<BeginShowToolTip>b__0(Object s, EventArgs e)
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at ApplicationName.App.Main()

**Comment by SamBent** [comment]
@kvijay22 - please attach a sample app, with precise steps to repro the crash.  Including exactly what you mean by "tool tip is invoked as soon as xaml is loaded".

We tried an app containing `<Button ToolTip="my tooltip"/>` and hovering the mouse over the button as soon as the xaml is loaded.  That doesn't crash.

**Comment by znakeeye** [comment]
No sample project needed. The exact commit is highlighted above - with a 100% valid fix. Please just push it now, and release 6.0.4 asap.

**Comment by batzen** [comment]
@znakeeye I strongly disagree that there is no repro needed as there seems to be a usage scenario neither the WPF team nor the tests are aware of. A repro is quite important to prevent issues in the future.
I strongly agree that this should be fixed as soon as possible. But without a repro the fix might be incomplete.

**Comment by znakeeye** [comment]
> @znakeeye I strongly disagree that there is no repro needed as there seems to be a usage scenario neither the WPF team nor the tests are aware of. A repro is quite important to prevent issues in the future. I strongly agree that this should be fixed as soon as possible. But without a repro the fix might be incomplete.

Usually, I would agree. This time, however, my experience tells me otherwise.

* Nobody will manage to create a repro project. It's a complex timing issue that occurs intermittently in rather complex scenarios. E.g. virtualization, recycling, data templates, ContentControls, style triggers etc. Hovering different items...
* A null-check in 6.0.3 would have given us some time to breathe.

**Root cause**
Anyway, the real bug can be found at [PopupControlService.cs(478)](https://github.com/dotnet/wpf/blob/869d4e0ec775d51ca50544a2473aafff1c1da813/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs#L478). There you have it. A memory leak which explains why `CloseToolTip()` is intermittently called for non-owned **dangling** objects.

```c#
CurrentToolTipTimer.Tick += new EventHandler(OnShowDurationTimerExpired);
```

On all places where `CurrentToolTipTimer` is re-assigned, you must remove that `Tick` handler. I suppose this memory leak could break tooltips in other ways too.

**Comment by hhu-mahmoud** [comment]
@SamBent unfortunately the problem still with the new .Net Version 6.0.4 and nothing is getting better.
We have been downgraded the system to .Net 5, because it's stable and after every update for .Net we let one employee to test .Net 6 until the app crashs. This time the app crashes after about 3 Hours without intensive working!!

-- if A null-check can give us something to breathe and it could solve the problem! So where the problem of making a Null-Check ?

The problem is not new and it dosen't solve until today and the .Net 5 is not the solution for this problem, because we will be not uptodate! Unfortunately we are thinking now to stop using WPF and stay by Winforms and ASP.

I don't know, how it will be with .Net 7. I hope that, they do not have like this problem.

------------------------------------------
Anyway here is the result of the exception and we hope to find the solution in .Net 6.0.5!!:

**XML:**

  <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022-04-25T12:18:03.334813900Z" /> 
  <EventRecordID>45525</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC1388</Computer> 
  <Security /> 
  </System>
  <EventData>
  <Data>Application: Project.exe CoreCLR Version: 6.0.422.16404 .NET Version: 6.0.4 Description: The process was terminated due to an unhandled exception. Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'element') at System.Windows.Controls.ToolTipService.GetBetweenShowDelay(DependencyObject element) at System.Windows.Controls.PopupControlService.CloseToolTip(ToolTip tooltip) at System.Windows.Controls.PopupControlService.OnPostProcessInput(Object sender, ProcessInputEventArgs e) at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(Tuple`2 postProcessInput, ProcessInputEventArgs processInputEventArgs) at System.Windows.Input.InputManager.ProcessStagingArea() at System.Windows.Input.MouseDevice.Synchronize() at System.Windows.Input.MouseDevice.ChangeMouseCapture(IInputElement mouseCapture, IMouseInputProvider providerCapture, CaptureMode captureMode, Int32 timestamp) at System.Windows.Input.MouseDevice.Capture(IInputElement element, CaptureMode captureMode) at CefSharp.Wpf.ChromiumWebBrowser.OnMouseDown(MouseButtonEventArgs e) in C:\projects\cefsharp\CefSharp.Wpf\ChromiumWebBrowser.cs:line 2239 at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e) at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args) at System.Windows.Input.InputManager.ProcessStagingArea() at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport) at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel) at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg) at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame) at System.Windows.Threading.Dispatcher.Run() at System.Windows.Application.RunDispatcher(Object ignore) at System.Windows.Application.RunInternal(Window window) at System.Windows.Application.Run() at Application.Desktop.App.Main()</Data> 
  </EventData>
  </Event>

--------------------------------------------------------------------------------------
**Exception:**

Application: Project.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
   at System.Windows.Controls.ToolTipService.GetBetweenShowDelay(DependencyObject element)
   at System.Windows.Controls.PopupControlService.CloseToolTip(ToolTip tooltip)
   at System.Windows.Controls.PopupControlService.OnPostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(Tuple`2 postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.MouseDevice.Synchronize()
   at System.Windows.Input.MouseDevice.ChangeMouseCapture(IInputElement mouseCapture, IMouseInputProvider providerCapture, CaptureMode captureMode, Int32 timestamp)
   at System.Windows.Input.MouseDevice.Capture(IInputElement element, CaptureMode captureMode)
   at CefSharp.Wpf.ChromiumWebBrowser.OnMouseDown(MouseButtonEventArgs e) in C:\projects\cefsharp\CefSharp.Wpf\ChromiumWebBrowser.cs:line 2239
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Application.Desktop.App.Main()
   
   
   -----------------------------------------------
   **XML**
   
   <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022-04-25T12:18:03.516031500Z" /> 
  <EventRecordID>45526</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC1388</Computer> 
  <Security /> 
  </System>
  <EventData>
  <Data>BibliothekSystem.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>61e1d8d9</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.17763.2803</Data> 
  <Data>bfcd0c87</Data> 
  <Data>e0434352</Data> 
  <Data>0000000000039319</Data> 
  <Data>2094</Data> 
  <Data>01d8589e2484668b</Data> 
  <Data>C:\Program Files\Project\Project.exe</Data> 
  <Data>C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data>108bbd7d-0ede-41d2-a40f-55b762a52ac3</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
  
----------------------------------------------------------------------
**Exception**
  
Name der fehlerhaften Anwendung: Project.exe, Version: 1.0.0.0, Zeitstempel: 0x61e1d8d9
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.17763.2803, Zeitstempel: 0xbfcd0c87
Ausnahmecode: 0xe0434352
Fehleroffset: 0x0000000000039319
ID des fehlerhaften Prozesses: 0x2094
Startzeit der fehlerhaften Anwendung: 0x01d8589e2484668b
Pfad der fehlerhaften Anwendung: C:\Program Files\Project\Project.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 108bbd7d-0ede-41d2-a40f-55b762a52ac3
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by znakeeye** [comment]
> -- if A null-check can give us something to breathe and it could solve the problem! So where the problem of making a Null-Check ?
> 

A null-check would indeed allow your app to run for more than 3 hours. But instead you would end up with even more leaked timers, causing an overall performance degradation. Your app would stop working at some point.

As I see it, we have **three viable options**:

1. Run .NET 5 until Microsoft fixes this.
2. Create a PR with a fix. That means fixing the memory leak. Not just a null-check!
3. Use a workaround. (Working on it.)

**Comment by znakeeye** [comment]
@hhu-mahmoud Can you please check if your app runs under 100% DPI setting when the crash occurs?

Tooltips are still broken in .NET 6.0.4 when running with higher System DPI. E.g. 150%.

**Comment by SamBent** [comment]
@hhu-mahmoud @kvijay22 et al. - please provide a repro.  If that's not possible, provide a [time-travel trace](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-record#attach-to-a-process) of the crashing scenario.  (It seems to involve opening a tooltip while another tooltip is already open, so be sure the trace includes opening the earlier tooltip.)

I don't doubt that there's a bug here.  But we need the repro (or trace) to understand how to fix the full scenario.  Adding a null check may not address deeper issues, but instead will make them much harder to find and fix.

@znakeeye - what's leaking?  The code you cite only adds references to the new EventHandler and to the PopupControlService itself.  Both references go away when the timer is cleared in `ResetCurrentToolTipTimer`, which is called in many places including when the tooltip closes.   There's no leak, at least not when the tooltips are opened and closed in the standard ways.

**Comment by EamonHetherton** [comment]
I have been able to reliably reproduce the problem in my application now, though the application is quite large so I'm trying to reduce it to a simple demo application (not as simple as I had hoped).

Essentially, the full application does background updates that can affect the layout on the screen (e.g. ItemsControl bound to an ObservableCollection<> of view models that change.

If I have the tooltip showing for one of the records when the update happens and that record is removed, I get the error every time.  I'll try to produce a reproduction application and submit.

**Comment by EamonHetherton** [comment]
Unfortunately I've not been able to reproduce the problem in a simple application but I've also discovered that in my actual application the issue is no longer reproducible after runtime 6.0.3.  Our current release is targeting 6.0.1 and I am able to trigger the issue on 6.0.1 and 6.0.2, but 6.0.3, 6.0.4 and 6.0.5 all appear to have the issue solved in my case at least.

**Comment by pchaurasia14** [comment]
@hhu-mahmoud  - Are you seeing this issue with 6.0.5 as well ?

**Comment by hhu-mahmoud** [comment]
@pchaurasia14 - We are still using .Net5 but i will tell one from the employee to make a test again. 
I updated now all packages in the project and also the .Net 6 version for the employees PCs to .Net 6.0.5 . As soon as I get the result, then i will post it here.

**Comment by hhu-mahmoud** [comment]
@pchaurasia14 Now I received the Info, that the Bug still exist. The App still crashes !!

**Comment by znakeeye** [comment]
> @znakeeye - what's leaking? The code you cite only adds references to the new EventHandler and to the PopupControlService itself. Both references go away when the timer is cleared in `ResetCurrentToolTipTimer`, which is called in many places including when the tooltip closes. There's no leak, at least not when the tooltips are opened and closed in the standard ways.

Try adding some error checking then. When assigning the timers, they must be null - or you will have a leak. Otherwise throw an exception. Personally, I would just make sure the timers are cleared before assigning them:
```c#
ResetCurrentToolTipTimer(); // Just in case
CurrentToolTipTimer = new DispatcherTimer(DispatcherPriority.Normal);
```

The same goes for that `PendingToolTipTimer`.

Or wait a few years for a repro. The conditions for this to happen are just too complex. Without some defensive error checking, you will never be able fix this bug.

**Comment by singhashish-wpf** [comment]
@znakeeye would you like to submit a PR for this?
However, we will still need some consistent and reliable way to reproduce the issue to get the fix in.

**Comment by SamBent** [comment]
I think I've found the cause (or at least a cause) for this crash.  I don't have a repro yet, but I wanted to share my theory first, and ask the community if it makes sense in your environment.

I've spent the last few days staring at our code, looking for some way this crash could occur.  This afternoon, after giving up on figuring it out, I started to write up my observations for the benefit of whoever carries the investigation forward.  Sparing you the first five pages, I got to this:

```
Putting all this together, the crash can only happen after the following sequence of activity:
1. `ShowToolTip` 
   * sets `_currentToolTip` 
   * sets Owner (to non-null, guaranteed)
   * sets `IsOpen` = true
2. (unknown) sets `IsOpen` = false
3. `ClearServiceProperties` clears Owner property
4. (unknown) sets `IsOpen` = true
5. `DismissCurrentToolTip` clears `_currentToolTip`
6. `CloseToolTip`
    * calls `GetOwner` and gets null
    * calls `tooltip.IsOpen` and gets true
```
Then I started to write a section on how our code certainly doesn't toggle `IsOpen`, it would be difficult for user code to do it except in special cases, and why would anyone do that anyway.  When on a hunch I looked back at the CefSharp code @amaitland  linked last March and found that's exactly what it does.  (You have to look at the third link, and go a little past where the link lands.)

So my theory is that the root cause is user code toggling tooltip.IsOpen, leaving the tooltip without an owner (because of step 3).  When the tooltip is later dismissed for real, `CloseToolTip` crashes.

This explains the CefSharp crashes.  (I don't know what causes CefSharp to call its `UpdateToolTip` method while the tooltip is already open, but @amaitland probably can explain that.)  My question to the community is does it explain your crashes?  In other words, does your app, or a library that it uses, manipulate ToolTip objects directly?  Specifically, does it toggle tooltip.IsOpen?

(BTW, with a time-travel trace I would have figured this out in an hour or so.)

**Comment by znakeeye** [comment]
> This explains the CefSharp crashes. (I don't know what causes CefSharp to call its `UpdateToolTip` method while the tooltip is already open, but @amaitland probably can explain that.) My question to the community is does it explain your crashes? In other words, does your app, or a library that it uses, manipulate ToolTip objects directly? Specifically, does it toggle tooltip.IsOpen?

**No**, not directly. We saw the crash in a `ComboBox` derived class where the `Popup.IsOpen` property is set in two different ways. Does that help in any way?


The only tooltip-related code I could find in our code base is **this** (performed on startup):
```c#
ToolTipService.ShowDurationProperty.OverrideMetadata(
    typeof(DependencyObject),
    new FrameworkPropertyMetadata { DefaultValue = 12000 });
```

Otherwise, the only `IsOpen` references are related to the `Popup` class...

```c#
ComboBox.IsDropDownOpenProperty.OverrideMetadata(typeof(MyComboBox),
    new FrameworkPropertyMetadata(false,
        FrameworkPropertyMetadataOptions.BindsTwoWayByDefault,
        OnIsDropDownOpenChanged,
        CoerceIsDropDownOpen));

// In OnIsDropDownOpenChanged callback, when IsMouseOver is false:
PART_Popup.SetCurrentValue(Popup.IsOpenProperty, false);
```

And in template:
```xaml
<Popup x:Name="PART_Popup"
       StaysOpen="True"
       IsOpen="{Binding IsDropDownOpen,RelativeSource={RelativeSource TemplatedParent}}"
       PopupAnimation="{DynamicResource MyPopupAnimation">
```

**Comment by hhu-mahmoud** [comment]
> I think I've found the cause (or at least a cause) for this crash. I don't have a repro yet, but I wanted to share my theory first, and ask the community if it makes sense in your environment.
> 
> I've spent the last few days staring at our code, looking for some way this crash could occur. This afternoon, after giving up on figuring it out, I started to write up my observations for the benefit of whoever carries the investigation forward. Sparing you the first five pages, I got to this:
> 
> ```
> Putting all this together, the crash can only happen after the following sequence of activity:
> 1. `ShowToolTip` 
>    * sets `_currentToolTip` 
>    * sets Owner (to non-null, guaranteed)
>    * sets `IsOpen` = true
> 2. (unknown) sets `IsOpen` = false
> 3. `ClearServiceProperties` clears Owner property
> 4. (unknown) sets `IsOpen` = true
> 5. `DismissCurrentToolTip` clears `_currentToolTip`
> 6. `CloseToolTip`
>     * calls `GetOwner` and gets null
>     * calls `tooltip.IsOpen` and gets true
> ```
> 
> Then I started to write a section on how our code certainly doesn't toggle `IsOpen`, it would be difficult for user code to do it except in special cases, and why would anyone do that anyway. When on a hunch I looked back at the CefSharp code @amaitland linked last March and found that's exactly what it does. (You have to look at the third link, and go a little past where the link lands.)
> 
> So my theory is that the root cause is user code toggling tooltip.IsOpen, leaving the tooltip without an owner (because of step 3). When the tooltip is later dismissed for real, `CloseToolTip` crashes.
> 
> This explains the CefSharp crashes. (I don't know what causes CefSharp to call its `UpdateToolTip` method while the tooltip is already open, but @amaitland probably can explain that.) My question to the community is does it explain your crashes? In other words, does your app, or a library that it uses, manipulate ToolTip objects directly? Specifically, does it toggle tooltip.IsOpen?
> 
> (BTW, with a time-travel trace I would have figured this out in an hour or so.)


Here is the exception from last test from 31.08.2022

Application: Project.exe
CoreCLR Version: 6.0.822.36306
.NET Version: 6.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
   at System.Windows.Controls.ToolTipService.GetBetweenShowDelay(DependencyObject element)
   at System.Windows.Controls.PopupControlService.CloseToolTip(ToolTip tooltip)
   at System.Windows.Controls.PopupControlService.PromotePendingToolTipToCurrent(TriggerAction triggerAction)
   at System.Windows.Controls.PopupControlService.<>c__DisplayClass9_0.<BeginShowToolTip>b__0(Object s, EventArgs e)
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Project.App.Main()




**We don't use any tooltip** in the App and we still wondering, why it comes again and again!!

**Comment by SamBent** [comment]
@znakeeye  - If you (or a library you're using) isn't changing ToolTip.IsOpen or Popup.IsOpen, I don't see how the crash can occur.  Please share a repro or a time-travel trace.

My argument runs as follows:  `PopupControlService` sets the (internal) Owner property to non-null before setting `tooltip.IsOpen = true` to show the tooltip (in `ShowToolTip`).   It's only cleared in `ClearServiceProperties` after `tooltip.IsOpen` is reset to false.  This can happen in response to the `ToolTip.Closed` event, or when the `ForceClose` timer ticks.  Both of these happen _after_ the crashing code in `CloseToolTip`, unless an outside agent does something to cause `ToolTip.Closed` to be raised.

Your earlier remarks about timers don't affect this - the timers don't inject `Closed` events.  Also, all the timers follow the "one-tick" pattern:  the timer is stopped and released after the first tick (if not earlier).  This avoids leaks and unexpected ticks.

@hhu-mahmoud - According to your early remarks, your app uses the CefSharp library, specifically `ChromiumWebBrowser`.   This means your app, _or a library it uses_, manipulates ToolTip objects directly.

Also, re-posting the same call stack doesn't add anything to the discussion.  We already know that the damage occurs much earlier (when the alleged direct manipulation occurs);  a callstack or even a crash dump won't explain the problem.  A repro or a time-travel trace would.

Everyone - I was able to repro the problem by adding direct manipulation, but it took more than simply copying the CefSharp code.  The code does toggle `tooltip.IsOpen` to false then back to true, but that wasn't enough to raise the `Closed` event.  There's some asynchronous activity in the parent `Popup` that needs to happen before the events get raised. 

This means that direct manipulation by itself may not be enough to explain the problem.  There's something else that enables the direct manipulation to raise the events, or there's a completely different route to the crash that we haven't considered yet.  As always, a repro or a time-travel trace would be very helpful.

**Comment by znakeeye** [comment]
Maybe it could happen via some automation APIs? We have automation IDs on pretty much all UI elements.

Also, we haven't seen this crash on our end since January. Maybe one of those tooltip related bug fixes in 6.0x _partially_ fixed this error.

**Comment by czdietrich** [comment]
We need to find a solution for this issue. We still receive crash reports for this issue and to be fair, it is kind of embarrassing for us to receive negative feedback about an issue we cannot really change anything about.

Crashing the whole application just because there is some issue with closing a tooltip feels just completely wrong.
Even though we are not able to reproduce the origin of this issue, we know it started to occur after latest changes to the tooltip behavior in WPF.

While I am not a fan of fixing symptoms, I am even less a fan of apologizing to customers when they lose their current progress just because of this tooltip issue.

Can we at least provide a workaround to just not throw this exception (e.g. with an app switch) even though we expect it usually not to happen?

**Comment by miloush** [comment]
@czdietrich Have you tried Switch.UseLegacyToolTipDisplay?

**Comment by znakeeye** [comment]
> 

If that setting avoids the crash, everybody will start using it - and this bug will never be fixed... 🤣

**Comment by SioGabx** [comment]
> @czdietrich Have you tried Switch.UseLegacyToolTipDisplay?

Never heard of this property, how to use it?

**Comment by czdietrich** [comment]
> @czdietrich Have you tried Switch.UseLegacyToolTipDisplay?

Thank you for the suggestion. This is the first time I read about this switch. A quick search led me to this [article](https://learn.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility#windows-presentation-foundation-wpf-1) and it seems to be related to .NET Framework 4.8 what predates the tooltip issue we face here, so I don't think it has an effect on the issue.

And since the issue occurs randomly for some users, I cannot really test whether it would work around this very issue and simply setting that switch in a service pack without knowing the result, seems not like the right way here.

**Comment by jaapversloot** [comment]
We encounter the same issue as described by @fresche-gavin. 

Setup:
- Windows 10
- .net 6.0.8
- CefSharp.Wpf.NETCroe 96.0.180

What seems to help is to remove the title attribute from all the buttons etc.

**Comment by czdietrich** [comment]
We encounter the same issue even without using CefSharp. While we were also using CefSharp to show web content, we switched to WebView2 some time ago and still see this issue. 

In our case the application is mixed WinForms / WPF and the crashes are not necessarily related to showing web content.

Setup: Windows 10, .NET 6.0.8

**Comment by mol** [comment]
We're using CefSharp and seeing it about 600 times a day for our users.

~95% are on Windows 11. I understand that a time-travel trace might help, so we'll try and get one. So far we've been unable to reproduce it internally.

**Comment by czdietrich** [comment]
If I understood correctly, they can already [reproduce the issue](https://github.com/dotnet/wpf/issues/7002#issuecomment-1290744979) and have a fix for it. But unfortunately, there is no new information since.

**Comment by hhu-mahmoud** [comment]
We have since 4 days changed from .Net5 to .Net7 (Desktop Runtime Version 7.0.2) => Everything looks fine since 4 days and we have no problems until now!

**Comment by czdietrich** [comment]
I am uncertain that it is actually fixed in .NET 7, since the related PR is sill open. 
But I can tell that the tooltip issue still exists in the latest version of .NET 6 (6.0.13), which is LTS and therefore needs to be fixed finally.

**Comment by werksarztzentrum** [comment]
We need also a quick fix for .NET Framework 4.8, all our Windows 11 Users have this problem in WPF.

**Comment by Lumoryel** [comment]
I have this exception in a **.NET Framework 4.8** WPF Application.
I debugged and saw that PopupControlService.CloseToolTip is called.
This method is not existing in the reference source for .NET Framework 4.8, at least what I have found here:

https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/PopupControlService.cs,595

Also the code here can not lead to this exception, because "o" is checked for null before.
Is this not the current .NET Framework 4.8 Source code?

**Comment by znakeeye** [comment]
> I can reproduce this exception in a **.NET Framework 4.8** WPF Application. I debugged and saw that PopupControlService.CloseToolTip is called. This method is not existing in the reference source for .NET Framework 4.8, at least what I have found here:
> 
> https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/PopupControlService.cs,595
> 
> Also the code here can not lead to this exception, because "o" is checked for null before. Is this not the current .NET Framework 4.8 Source code?
> 
> It happens to me since I have a new computer with windows 11. But it also happened to a colleague with windows 10 19045 (like my old computer, where the exception never showed up)

You are probably running `4.8.1` even though you're targeting `4.8`.

**Comment by Lumoryel** [comment]
Good point @znakeeye ! That's it thank you.

On my new computer:
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\Release = 533320 = 4.8.1`

On my old computer:
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\Release = 528372 = 4.8`

So https://referencesource.microsoft.com/ shows only 4.8 code.
Where can I find the 4.8.1 code ?

Maybe the main description of this issue should state that it also happens in 4.8, if 4.8.1 is installed?

**Comment by fresche-gavin** [comment]
@Lumoryel @znakeeye  Yes, as previously mentioned, we could not replicate it in .Net 4.8, but can replicate it in .Net 4.8.1 (both on Windows 10). 

For the time being, one of our devs (@cmunforte) found a workaround fix mentioned here: https://github.com/cefsharp/CefSharp/issues/4048#issuecomment-1436128147

**Comment by dipeshmsft** [comment]
@czdietrich @hhu-mahmoud @znakeeye  can you verify if the latest release ( 7.0.5 / 6.0.16 ) resolves issues in your applications ?

**Comment by hhu-mahmoud** [comment]
@dipeshmsft since the Update 7.0.2 and now 7.0.5 I have received no complaint from the employees. Everything works fine.

I don't know about .Net6, cus we already updated to .Net7 since few months.

**Comment by dipeshmsft** [comment]
Thanks @hhu-mahmoud for the confirmation. Closing this issue now.

**Comment by Lumoryel** [comment]
Please consider that "Does the bug reproduce also in WPF for .NET Framework 4.8?: No" is not really correct.
It happens on Windows 11 with a .NET Framework 4.8 targeted program. Is it possible to change that on the initial post?

**Comment by dipeshmsft** [comment]
@Lumoryel, this fix has been included in .NET Framework 4.8.1 as well. Is that what you were asking here?

**Comment by Lumoryel** [comment]
@dipeshmsft The fact that 4.8.1 code is running although target is 4.8 (but only on windows 11) confused me alot. If this would be stated somehow in the first post, would have helped me alot.
