### ISSUE TITLE
In the .net7 CollectionViewSource has a different behaviour than in the .net6

### ISSUE THREAD

**Issue by danielkaczmarek** [dotnet/wpf#7291]
Basically, in .net7 when you run the attached project and press the button, it will display a list of items. If you run the unit test it will throw an exception on this line 

` EntityCollectionView = new CollectionViewSource { Source = Entities }.View;`

Because the View is null.

If you change the TargetFramework to net6 the test passes because View contains an instance. 

Is this a bug?

Regards
Daniel Kaczmarek

[WpfApp2.zip](https://github.com/dotnet/core/files/10012439/WpfApp2.zip)

**Comment by steveharter** [comment]
Appears to be related or a duplicate of https://github.com/dotnet/wpf/issues/7205

Callstack:
```
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
   at System.Windows.StyleHelper.GetExpression(DependencyObject d, DependencyProperty dp)
   at System.Windows.Data.BindingOperations.GetBindingExpressionBase(DependencyObject target, DependencyProperty dp)
   at System.Windows.Data.CollectionViewSource.<EnsureView>b__103_0(Object x)
   at MS.Internal.Data.ViewManager.EnsureCollectionRecord(Object collection, Func`2 GetSourceItem)
   at MS.Internal.Data.ViewManager.GetExistingView(Object collection, CollectionViewSource cvs, Type collectionViewType, Func`2 GetSourceItem)
   at MS.Internal.Data.ViewManager.GetViewRecord(Object collection, CollectionViewSource cvs, Type collectionViewType, Boolean createView, Func`2 GetSourceItem)
   at MS.Internal.Data.DataBindEngine.GetViewRecord(Object collection, CollectionViewSource key, Type collectionViewType, Boolean createView, Func`2 GetSourceItem)
   at System.Windows.Data.CollectionViewSource.EnsureView(Object source, Type collectionViewType)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at WpfApp2.MainWindowViewModel.CreateEntityCollectionView() in C:\temp\Wpf2App\WpfApp2\WpfApp2\MainWindowViewModel.cs:line 33
   at TestProject1.Tests.Test1() in C:\temp\Wpf2App\WpfApp2\TestProject1\UnitTest1.cs:line 18
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by lindexi** [comment]
See https://github.com/dotnet/wpf/discussions/7218

**Comment by tisis2** [comment]
same issue here. i wanted to update to net7 but my viewmodel unit tests are failing because they contain the collectionviewsource. i did a quick and easy repro:
![image](https://user-images.githubusercontent.com/18416393/202127512-5275dabf-12b0-4658-829b-f1d0c837ab97.png)
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Windows.StyleHelper.GetExpression(DependencyObject d, DependencyProperty dp)
   at System.Windows.Data.BindingOperations.GetBindingExpressionBase(DependencyObject target, DependencyProperty dp)
   at System.Windows.Data.CollectionViewSource.<EnsureView>b__103_0(Object x)
   at MS.Internal.Data.ViewManager.EnsureCollectionRecord(Object collection, Func`2 GetSourceItem)
   at MS.Internal.Data.ViewManager.GetExistingView(Object collection, CollectionViewSource cvs, Type collectionViewType, Func`2 GetSourceItem)
   at MS.Internal.Data.ViewManager.GetViewRecord(Object collection, CollectionViewSource cvs, Type collectionViewType, Boolean createView, Func`2 GetSourceItem)
   at MS.Internal.Data.DataBindEngine.GetViewRecord(Object collection, CollectionViewSource key, Type collectionViewType, Boolean createView, Func`2 GetSourceItem)
   at System.Windows.Data.CollectionViewSource.EnsureView(Object source, Type collectionViewType)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at TestProject1.Tests.Test1() in C:\work\src\DevExpressIssueExamples\TestProject1\TestProject1\UnitTest1.cs:line 11
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)



-----

One or more child tests had errors
  Exception doesn't have a stacktrace
```

**Comment by pchaurasia14** [comment]
While we've merged the PR on the `main` branch, we will also be releasing the fix for .NET 7 servicing branch.

**Comment by olivierhelin** [comment]
Hello,
We tried with .Net SDK 7.0.300-preview.23101.17 and we still have this issue with our unit tests. Do you know in which version of the sdk the fix will be available?

Regards,
Olivier Helin

**Comment by wlaroche** [comment]
Hello, What is the state of this behavior ? bug ? if true, when could you think to be fix this ?
Thank :)
Wil

**Comment by ThomasGoulet73** [comment]
I believe the fix is already in the release/7.0 branch but it was is not included in a release yet. I should be included in the upcoming .Net 7.0.3.
