### ISSUE TITLE
Windows 11 Theming Does Not Work In PowerShell WPF Window

### ISSUE THREAD

**Issue by nkasco** [dotnet/wpf#9373]
### URL(s)

https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview4/9.0.0-preview.4.md

### Description

The following code should render a Windows 11 style WPF Window in PowerShell 7 (fx dependent, using .NET 9 Preview 4)

```
Add-Type -AssemblyName PresentationFramework

[xml]$xaml = @"
<Window
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    x:Name="Window">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/PresentationFramework.Fluent;component/Resources/Fluent.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>
    <StackPanel>
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Center">
            <TextBox x:Name="MyTextBox" Width="150" />
            <Button x:Name="SubmitButton" Content="Submit" Margin="5" />
        </StackPanel>
    </StackPanel>
</Window>
"@

$reader = (New-Object System.Xml.XmlNodeReader $xaml)
$window = [Windows.Markup.XamlReader]::Load($reader)

$window.ShowDialog()
```

**Current Result:** Black window, although I can tell the elements are there because if I hover over the textbox my cursor changes. Doesn't appear to be properly loading the ResourceDictionary
![image](https://github.com/dotnet/core/assets/1930697/0619b8f6-0254-47af-b4c9-53f5acb300bf)

Confirmed that my PowerShell 7 console is using .NET 9 preview 4:
```
> [System.Runtime.InteropServices.RuntimeInformation]::FrameworkDescription
.NET 9.0.0-preview.4.24266.19
```

Perhaps I am just missing something beyond adding the proper ResourceDictionary?

**Comment by dipeshmsft** [comment]
@nkasco, can you tell me if there is a way to test this with a local set of binaries ? We have just merged the Theme switching APIs, and wanted to test this with the recent changes.

**Comment by nkasco** [comment]
> @nkasco, can you tell me if there is a way to test this with a local set of binaries ? We have just merged the Theme switching APIs, and wanted to test this with the recent changes.

@dipeshmsft 
I have been using the fxdependent version of PowerShell: https://github.com/PowerShell/PowerShell/releases/download/v7.4.4/PowerShell-7.4.4-win-fxdependentWinDesktop.zip 

If that doesn't work, instead of `Add-Type -AssemblyName PresentationFramework` you could try `Add-Type -Path "path\to\PresentationFramework.dll"` (might also need to load in PresentationFramework.Fluent.dll if you do that)

**Comment by nkasco** [comment]
@dipeshmsft Still not working in .NET 9 preview 7, although the resource path changed per #9580 

Updated test script:
`Add-Type -AssemblyName PresentationFramework

[xml]$xaml = @"
<Window
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    x:Name="Window">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/PresentationFramework.Fluent;component/Themes/Fluent.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>
    <StackPanel>
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Center">
            <TextBox x:Name="MyTextBox" Width="150" />
            <Button x:Name="SubmitButton" Content="Submit" Margin="5" />
        </StackPanel>
    </StackPanel>
</Window>
"@

$reader = (New-Object System.Xml.XmlNodeReader $xaml)
$window = [Windows.Markup.XamlReader]::Load($reader)

$window.ShowDialog()
`

**Comment by dipeshmsft** [comment]
The changes to fix this have finally made it in .NET 9 RC1. Can you give it a try with the latest RC1 / RC2 release ?

**Comment by HotCakeX** [comment]
> The changes to fix this have finally made it in .NET 9 RC1. Can you give it a try with the latest RC1 / RC2 release ?

Where can we download them? the latest available one i see is preview 7
https://dotnet.microsoft.com/en-us/download/dotnet/9.0

**Comment by dipeshmsft** [comment]
You can download the latest daily build from here : https://github.com/dotnet/sdk/blob/main/documentation/package-table.md

**Comment by HotCakeX** [comment]
> You can download the latest daily build from here : https://github.com/dotnet/sdk/blob/main/documentation/package-table.md

Thank you! I downloaded the RC2 version, and I ran this PowerShell code in the PowerShell fxdependent edition that doesn't bundle the .NET dlls by default

```powershell
Get-ChildItem -Filter '*.dll' -File -Path 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\9.0.0-rc.2.24425.1\' | ForEach-Object {
    try {
        Add-Type -Path $_.FullName
    }
    catch {}
}

[xml]$xaml = @'
<Window
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    x:Name="Window">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/PresentationFramework.Fluent;component/Themes/Fluent.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>
    <StackPanel>
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Center">
            <TextBox x:Name="MyTextBox" Width="150" />
            <Button x:Name="SubmitButton" Content="Submit" Margin="5" />
        </StackPanel>
    </StackPanel>
</Window>
'@

$reader = (New-Object System.Xml.XmlNodeReader $xaml)
$window = [Windows.Markup.XamlReader]::Load($reader)

$window.ShowDialog()
```

But what I'm seeing is this

![image](https://github.com/user-attachments/assets/1db115e4-9db8-4faf-b8b1-009a829e2ac7)

<br>

<br>

Is it possible to provide a working example for PowerShell? WPF has been used in PowerShell for a long time and this change is really big and I'm hoping we'll be able to use it too.

**Comment by nkasco** [comment]
@dipeshmsft We are in business! I didn't do an extensive test on all object types, but definitely seems to be propagating the theming from the Window element now.

![image](https://github.com/user-attachments/assets/433b52f9-9a72-4882-ae9a-956b9dc1039c)

If I find anything odd I will report it back here. If I don't find anything in the next week, or unless you know of an reason otherwise, at that point we can probably close this one out.

**Comment by dipeshmsft** [comment]
If I am not wrong, I think I saw a comment stating otherwise yesterday. What was the issue earlier ?
I also wanted to state that you can give `Window.ThemeMode` property a try.

**Comment by HotCakeX** [comment]
> If I am not wrong, I think I saw a comment stating otherwise yesterday. What was the issue earlier ? I also wanted to state that you can give `Window.ThemeMode` property a try.

You're right, i posted a comment before but deleted it because i figured it out.

Can we use the new Windows 11 style themes on `<UserControl>` elements too? because it doens't seem to work when I try it like this

```xaml
    <UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/PresentationFramework.Fluent;component/Themes/Fluent.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>
```

in

```powershell
Add-Type -Path 'C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\9.0.0-rc.2.24425.1\PresentationFramework.dll'

[xml]$xaml = @'
<UserControl xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/PresentationFramework.Fluent;component/Themes/Fluent.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>
    <StackPanel>
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Center">
            <TextBox x:Name="MyTextBox" Width="150" />
            <Button x:Name="SubmitButton" Content="Submit" Margin="5" />
        </StackPanel>
    </StackPanel>
</UserControl>
'@

$reader = (New-Object System.Xml.XmlNodeReader $xaml)
$userControl = [Windows.Markup.XamlReader]::Load($reader)

$window = New-Object System.Windows.Window
$window.Content = $userControl
$window.Width = 300
$window.Height = 200
$window.WindowStartupLocation = 'CenterScreen'
$window.Title = 'UserControl in Window'

$window.ShowDialog()
```

**Comment by dipeshmsft** [comment]
@HotCakeX , in this case you can make it work by setting `ThemeMode` on `window` rather than including the resource dictionary

**Comment by dipeshmsft** [comment]
@HotCakeX @nkasco thanks for bringing this issue. It took us some time to get to it but since this is fixed now, I am closing this issue now. If you have any more issues, feel free to open a new issue.

**Comment by HotCakeX** [comment]
@dipeshmsft Thank u very much!
